development:
  adapter: postgresql
  database: didact
  username: postgres
  password: password
  host: localhost

production:
  adapter: postgresql
  encoding: unicode
  pool: 5
  database: d76e7ao4akckgp
  username:
  password:
  host:
  port: 5432
